# Generated by Django 5.0.4 on 2024-05-22 15:58

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='titulo',
        ),
        migrations.AddField(
            model_name='cita',
            name='ap_mat',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='ap_pat',
            field=models.CharField(default=datetime.datetime(2024, 5, 22, 15, 57, 16, 216766, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='asunto',
            field=models.CharField(choices=[('Academica', 'Academica'), ('Personal', 'Personal'), ('Vocacional', 'Vocacional'), ('Baja', 'Baja'), ('Psicologica', 'Psicologica')], default='Academica', max_length=50),
        ),
        migrations.AddField(
            model_name='cita',
            name='carrera',
            field=models.CharField(choices=[('Ingenieria Civil', 'Ingenieria Civil'), ('Ingenieria en Electronica', 'Ingenieria en Electronica'), ('Ingenieria en Computacion', 'Ingenieria en Computacion'), ('Ingenieria Industrial', 'Ingenieria Industrial'), ('Ingenieria en Nanatecnologia', 'Ingenieria en Nanotecnologia'), ('Ingenieria en Software', 'Ingenieria en Software y Tecnologias Emergentes'), ('Bioingenieria', 'Bioingenieria'), ('Arquitectura', 'Arquitectura')], default='Ingenieria en Software', max_length=50),
        ),
        migrations.AddField(
            model_name='cita',
            name='descripcion',
            field=models.TextField(default=datetime.datetime(2024, 5, 22, 15, 57, 29, 742960, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='matricula',
            field=models.CharField(default=datetime.datetime(2024, 5, 22, 15, 57, 44, 275977, tzinfo=datetime.timezone.utc), max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='nombres',
            field=models.CharField(default=datetime.datetime(2024, 5, 22, 15, 57, 59, 232911, tzinfo=datetime.timezone.utc), max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='semestre',
            field=models.CharField(default=datetime.datetime(2024, 5, 22, 15, 58, 2, 927795, tzinfo=datetime.timezone.utc), max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Prefiero no decirlo', 'Prefiero no decirlo')], default='Prefiero no decirlo', max_length=20),
        ),
    ]
