# Generated by Django 5.0.4 on 2024-05-19 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alter_cita_estado_alter_cita_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='solicitada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
