# Generated by Django 5.0.4 on 2024-05-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='comentarios',
            field=models.TextField(default='No hay comentarios.', max_length=200),
        ),
    ]
