# Generated by Django 5.0.4 on 2024-05-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Declinada', 'Cancelada')], default='Pendiente', max_length=11),
        ),
    ]
