# Generated by Django 5.0.4 on 2024-05-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_cita_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='ap_materno',
            new_name='apellido_materno',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='ap_paterno',
            new_name='apellido_paterno',
        ),
    ]
