# Generated by Django 5.0.4 on 2024-05-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_rename_ap_materno_cita_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='semestre',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='1', max_length=2),
        ),
    ]
