# Generated by Django 5.0.4 on 2024-05-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_alter_cita_semestre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='comentarios',
            new_name='comentarios_orientador',
        ),
        migrations.AddField(
            model_name='cita',
            name='comentarios_usuario',
            field=models.TextField(default='No hay comentarios.', max_length=200),
        ),
    ]
